### ISSUE TITLE
BuildCraft Crash

### ISSUE THREAD

**Issue by FilipK-CZ** [Elecs-Mods/CraftingTable-IV#10]
http://pastebin.com/kL2HpXgJ

**Comment by Elec332** [comment]
Hmm, im not quite sure if this is an issue on my end, have you reported thsi to the BuildCraft Github aswell?

**Comment by FilipK-CZ** [comment]
Because it crash only after moving to the icon of a machine from buildcraft in your crafting.

**Comment by Elec332** [comment]
In the "chest" part, or the "crafting" part of the GUI?

**Comment by FilipK-CZ** [comment]
Crafting
