### ISSUE TITLE
Heavy Log Spam

### ISSUE THREAD

**Issue by Chocohead** [Elecs-Mods/CraftingTable-IV#12]
With the latest version in the latest version of Tekkit Legends, when you first load a world or open a Crafting Table IV, there's this spammed in the log: http://pastebin.com/gACeHdcg

It would suggest there's something wrong with the IC2 Classic and Forestry (3) handlers, as well as some mods that still don't have one like ProjectE and Logistics Pipes.

**Comment by Elec332** [comment]
It was intended to log when a handler doesnt exist, I forgot that you ofcourse have quite a few recipes with the same class, Ill m,ake sure to decrease the spamming.
