### ISSUE TITLE
Tiny Texture Bug

### ISSUE THREAD

**Issue by Chocohead** [Elecs-Mods/CraftingTable-IV#13]
The bottom panel is a pixel too short, you can see it when the door is open:
![2015-10-11_20 33 06](https://cloud.githubusercontent.com/assets/4021725/10418601/80c4e45e-7057-11e5-8572-152eadce59b8.png)
Crafting Table III had the same bug, and it becomes more pronounced if you use a higher resolution texture pack.

**Comment by Elec332** [comment]
Yea, Im using the same textures and renderers from CraftingTableIII, so it makes sense this mod also has that issue :P

I will look into this, but my priority goes to fixing compat handlers first :)

**Comment by HanPrower** [comment]
I'm going to throw this in here just so not to have more "texture bug" issues. Hope that's okay ;)

The model in hand is rotated 180 degrees:
![Upside down model](http://puu.sh/kT9My/753f75129b.png)

**Comment by Elec332** [comment]
@HanFox Haha, lol.

That will be an easy fix

**Comment by draknyte1** [comment]
11mo later~

**Comment by Elec332** [comment]
The rotation is fixed....

The 1-pixel-issue is a thing that I keep forgetting and that is actually quite low on my priority list.

**Comment by Elec332** [comment]
![image](https://user-images.githubusercontent.com/6115944/53645572-6feb3a00-3c39-11e9-8a69-d110a2a65fbb.png)

I was looking through the issues list when I found this, whoops.

After looking closely I saw that there was some Z-fighting, so it ended up being a translation/rotation issue.
