### ISSUE TITLE
Crafting Table IV doesnt work in SMP

### ISSUE THREAD

**Issue by mrdeadlocked** [Elecs-Mods/CraftingTable-IV#14]
We are running a kcauldron server and when trying to use crafting table iv it doesnt work. The GUI shows all of the items based on what you have in your inventory, but when y ou click them the gui just flashes. I can collect/get anything else you might need to help fix this. Just let me know.

**Comment by Elec332** [comment]
Log, Does it show any errors? (You can post it anyways if you're not sure)
Modlist would also be helpfull (Link to modpack even better)

**Comment by mrdeadlocked** [comment]
http://www.technicpack.net/modpack/falseprovince.732280 is the modpack. I can click the items inside of the crafting table GUI all day, and nothing shows in client logs or server logs.

**Comment by Elec332** [comment]
Hmm, does th background flash, the items flash, do both flash?
(Is it possible to show me a image/GIF/whatever?)

**Comment by mrdeadlocked** [comment]
I will get this for you in a couple hours.

**Comment by Elec332** [comment]
Thanks

**Comment by mrdeadlocked** [comment]
Here you go: https://www.dropbox.com/s/sv042m7nvaxbea7/Error.gif?dl=0

**Comment by Elec332** [comment]
Are you clicking the slot? Or just hovering over?
(Thanks for the gif btw :))

**Comment by mrdeadlocked** [comment]
Ya thats be clicking. I clicked it everytime it flashes thats me clicking.

**Comment by Elec332** [comment]
And it doesnt craft the items for you?

**Comment by mrdeadlocked** [comment]
Nope, No items crafted and no items consumed.

**Comment by quentfr21** [comment]
hello

same for me on forge server 
forge 10.13.4.1492

no prob in solo

**Comment by modern19999** [comment]
same problem. Kcauldron, forge 1517

**Comment by mrdeadlocked** [comment]
I'm glad its also a problem on forge!

**Comment by Elec332** [comment]
This is a networking issue.

**Comment by quentfr21** [comment]
hello

after some test on my server i found something strange 

wooden slab and fence icon
http://rousteurs.free.fr/test.png
and it craft me stone stair XD

split oak wood door from "extra trees" craft me a wooden stair

maybe this can help you to find pb

**Comment by draknyte1** [comment]
Any eta on a fix?
Just going to remove it and replace it with an alternative mod since you've been active on github without response here.

**Comment by Elec332** [comment]
Fixed on the latest version

**Comment by draknyte1** [comment]
Is the latest still for 1.7.10?

**Comment by Elec332** [comment]
Yes, 1.7.10 and 1.8.9/9

**Comment by milkyskies** [comment]
Hi, I am getting this on 1.10.2.
