### ISSUE TITLE
CTIV breaks OreDictionary

### ISSUE THREAD

**Issue by 4rz0** [Elecs-Mods/CraftingTable-IV#16]
I'm currently experimenting with 1.8.8 SSP.
There I noticed that when I have different types of wood in my inventory (let's say oak and dark oak), and I use the crafting table to create something out of wood, after that I can not create certain things from dark oak anymore (like chests, or even sticks).
The recipes are then also gone from the vanilla crafting table.
A client restart "fixes" that problem until I use the CTIV again.

**Comment by Elec332** [comment]
Fixed

**Comment by TheTrueLoki** [comment]
SP No other mods and with other mods.
CraftingTable-1.8.9-1.2.84
ElecCore-1.8.9-1.4.220   -   CTIV breaks OreDictionary
ElecCore-1.8.9-1.4.224   -   CTIV breaks OreDictionary
ElecCore-1.8.9-1.4.225   -   CTIV Crash
ElecCore-1.8.9-1.4.228   -   CTIV Crash
