### ISSUE TITLE
Crash with WAILA

### ISSUE THREAD

**Issue by BBoldt** [Elecs-Mods/CraftingTable-IV#17]
https://gist.github.com/a5b6ffdcba3c9a01ff82
- forge-1.8.8-11.15.0.1635-1.8.8-universal.jar
- ElecCore-1.8.8-1.4.200.jar
- CraftingTableIV-1.8.8-1.1Beta.71.jar
- Waila-1.6.0-B2_1.8.8.jar

**Comment by Elec332** [comment]
Ill fix this today

2015-12-18 3:32 GMT+01:00 BBoldt notifications@github.com:

**Comment by Elec332** [comment]
Note: This is an ElecCore issue, not an CTIV issue :)

2015-12-18 11:14 GMT+01:00 Arnout Mak arnout1998@gmail.com:
