### ISSUE TITLE
Nothing crafts at all

### ISSUE THREAD

**Issue by Hannah-GBS** [Elecs-Mods/CraftingTable-IV#23]
As of the time of writing this I'm using the latest version of the mod and latest ElecCore.
The game runs and the crafting table is in the decorations tab (testing in creative) and when I put things in the crafting table's inventory, the items to craft show up but clicking on them does nothing. The texture sometimes flickers a little but otherwise there's no indication that it's doing anything.
Using 1.8.9 with the latest Forge. Tried in creative and survival.

**Comment by Elec332** [comment]
Dedicated server or Single Player?
What other mods are installed?

**Comment by Hannah-GBS** [comment]
Single player. No other mods.

**Comment by Elec332** [comment]
Ohhh, I see a stupid mistake here...
