### ISSUE TITLE
crash minecraft 1.7.10

### ISSUE THREAD

**Issue by quentfr21** [Elecs-Mods/CraftingTable-IV#24]
hello 
latest CTIV
forge 1614

same as #20 (wrapped recipe crash)
i see a fix for 1.8.9 can you make it for 1.7.10 please

thanks

**Comment by draknyte1** [comment]
I asked him to do this a day or two after he release the 1.8 fixes.. Still waiting...

**Comment by Elec332** [comment]
Im very sorry, but I was (am) in the middle of a test week.
Ill fix it this weekend though.

**Comment by draknyte1** [comment]
You could respond to people via email, it takes two minutes.. Instead you ignored the fact it was only half fixed and closed the open issues. See #20 as a fine example..

Be sure to test against GregTech5U as priority, not GT6.

**Comment by quentfr21** [comment]
@Elec332 

thanks in advance
