### ISSUE TITLE
1.8.9 CTIV breaks OreDictionary

### ISSUE THREAD

**Issue by TheTrueLoki** [Elecs-Mods/CraftingTable-IV#27]
SP No other mods and with other mods.
CTIV breaks OreDictionary relog fixes for normal crafting benches and modded crafting grids until CTIV is used and then none of them can use the oreDictionary.

CraftingTable-1.8.9-1.2.84
ElecCore-1.8.9-1.4.220   -   CTIV breaks OreDictionary
ElecCore-1.8.9-1.4.224   -   CTIV breaks OreDictionary
ElecCore-1.8.9-1.4.225   -   CTIV Crashes
ElecCore-1.8.9-1.4.228   -   CTIV Crashes

**Comment by Elec332** [comment]
So, as far as I can see, it doesnt break the oredict anymore, it crashes?
In the case of a crash, I need a crashlog to be able to help you.

**Comment by TheTrueLoki** [comment]
Hmm...
MC 1.8.9
fml 11.15.1.1747

Core: 220
I can craft a pickaxe using spruce planks and sticks made out of spruce in a normal bench.
If i use the CTIV to make sticks, the spruce can no longer be used to make sticks in a normal bench nor in the CTIV. In fact the only things I can use spruce for is the spruce labeled items (door, stairs, slab).

![ctiv error](https://cloud.githubusercontent.com/assets/17349707/13207162/d6c39602-d8d0-11e5-85e6-5c3ebe0a1fc7.jpg)

The crashes are a relation to another issue where you stated "using a too new version" of elec core  crashes the CTIV, I used them to make sure it wasnt a version mismatch causing it.

Latest Core: 228
[Uploading crash-2016-02-21_19.03.11-server.txt…]()
Core: 224
[Uploading crash-2016-02-21_19.10.08-client.txt…]()
Core: 219
Minecraft stops > requests core version 220 then closes > no log generated.

**Comment by TheTrueLoki** [comment]
wrong button... *derp

**Comment by TheTrueLoki** [comment]
And for whatever reason github didn't want to accept the logs so here...

Core 228
[crash-2016-02-21_19.03.11-server.txt](https://github.com/Elecs-Mods/CraftingTable-IV/files/139978/crash-2016-02-21_19.03.11-server.txt)

Core 224
[crash-2016-02-21_19.10.08-client.txt](https://github.com/Elecs-Mods/CraftingTable-IV/files/139979/crash-2016-02-21_19.10.08-client.txt)

**Comment by ozBillo** [comment]
Still having OreDictionary problems. 
eg. can't craft sticks with Spruce Logs. Shows Spruce Planks but crashes when I try to craft them.

CraftingTableIV-1.8.9-1.2.84
ElecCore-1.8.9-1.4.271
Forge-1.8.9-11.15.1.1764
