### ISSUE TITLE
[Crash | Client] Compatibility Issue with JEI?

### ISSUE THREAD

**Issue by robaimes** [Elecs-Mods/CraftingTable-IV#28]
Simply browsing the JEI interface causes a crash sometimes. Last time, I searched `@Ti` before the crash occured. I was searching for Tinkers Construct, but CraftingTable-IV contains "ti" which is where I presume this issue stems from.

http://pastebin.com/HWt4e4X4

**Comment by ghost** [comment]
Seconded and repeatable (1.8.9). [crash log](https://paste.ee/p/Gyhnd) It seems to occur when the table is going to show up in JEI from a search. It seems to be the same as #29.

**Comment by Paradox** [comment]
are you able to create the table in the normal way, or, does it also crash then?

**Comment by ghost** [comment]
I couldn't even get the recipe.

**Comment by ghost** [comment]
Same problem here, incompatible with JEI.

http://paste.ee/p/oWTqp
