### ISSUE TITLE
Thermal Expansion Machines

### ISSUE THREAD

**Issue by crozear** [Elecs-Mods/CraftingTable-IV#33]
Some thermal expansion machines don't show up even when you have the right materials. The pulverizer and redstone furnace don't show up and some other ones could too. I think it has to do with the machines being under the same ID even though they have different recipes. I have minecraft version 1.7.10 with the crafting table 4 version 1.1Beta 82 with thermal expansion version 4.1.2-240.

**Comment by draknyte1** [comment]
I've found anything that uses its own recipe handler page within NEI (IC2 shaped crafting or Aromatic crafting - for example)  won't show up at all.

**Comment by crozear** [comment]
Hmm that is a big problem, hope it gets fixed soon. There also is just a lot of graphical glitches in general, It gets annoying after a while.

**Comment by Elec332** [comment]
Re-added the mod-support modules
