### ISSUE TITLE
Timeout on 1.7.10 Thermos Server

### ISSUE THREAD

**Issue by FireController1847** [Elecs-Mods/CraftingTable-IV#35]
This mod has a bug with Thermos server's where it will timeout the player every time they join. I don't know if this is a bug with my modpack or the server, but it caused all of my players to timeout.

It doesn't log anything in the output, it will literally just times players out and the server will not respond to players. Please, please fix this!

My Modlist:
[Mod Info.txt](https://github.com/Elecs-Mods/CraftingTable-IV/files/400987/Mod.Info.txt)

**Comment by Servovicis** [comment]
Experiencing the same issue with crafting on a Thermos server. All players eventually time out and after a min or so can reconnect.

**Comment by Elec332** [comment]
Please try again with latest version
