### ISSUE TITLE
Not crafting

### ISSUE THREAD

**Issue by b46saunders** [Elecs-Mods/CraftingTable-IV#38]
When running this on 1.10.2 with just ElecCore-1.10.2-1.6.333 and crafting table iv 1.2.100 I am unable to craft anything. I get no errors but just a flicker when clicking an item to craft. any suggestions?
forge-12.18.2.2147

**Comment by Pyrite19** [comment]
Same issue.

**Comment by ozBillo** [comment]
Same problem here with ElecCore-1.10.2-1.6.333 and CraftingTableIV-1.10.2-1.2.100. 

Any suggestions?

**Comment by florian-berger** [comment]
I am looking for a bugfix for Minecraft 1.10.2 - When can we expect it?

**Comment by Elec332** [comment]
Please try the latest version
