### ISSUE TITLE
Issue with Connecting to Server

### ISSUE THREAD

**Issue by Amaxter** [Elecs-Mods/CraftingTable-IV#4]
Causes a connection issue when trying to connect to a server with the mod as well: http://hastebin.com/huzetomiva.avrasm

**Comment by Elec332** [comment]
2 questions:
1) Are you useing the latest version on both the client AND the server
2) Can I see the modlist?

**Comment by Amaxter** [comment]
1) Yes, I am using the latest version of CraftingTable IV and Elec Core.
2) The mod list can be found here (sans your mods since I've removed them until this issue is resolved):
http://www.technicpack.net/modpack/core-zero.684136/mods

**Comment by Elec332** [comment]
Fixed in latest commit, It'll probably be live on curse in a few hours
