### ISSUE TITLE
crash with actually additions

### ISSUE THREAD

**Issue by meelock** [Elecs-Mods/CraftingTable-IV#43]
[crash on onedrive (Microsoft's google drive)](https://seattleschools-my.sharepoint.com/personal/man_ezpommert_seattleschools_org/_layouts/15/guestaccess.aspx?guestaccesstoken=EcnmJOnWy4Yi3IqU232xcJDyVFUikMb6WLddMRp5Hy4%3d&docid=0437be1fced4b4bfb8d3a78e88995a841&rev=1) i am not totally sure why this happens please figure it out if you can.

thanks!

- Meelock

**Comment by Elec332** [comment]
This is an issue on their side, please report it to them
