### ISSUE TITLE
Client crash when opening table

### ISSUE THREAD

**Issue by Dalethium** [Elecs-Mods/CraftingTable-IV#48]
Game type: Creative (maybe survival, untested)
Server type: Remote, lan, windows 10, java 8.
Client type: Windows 10, java 8
Crash log: https://pastebin.com/j6sKFHha
Notes: Convergence is a mod I have put together, should not affect this mod though.

Steps to reproduce: Server>Connect>Creative>Get Table>Place Table>Open Table>Crash.

Server DC message: https://pastebin.com/Kx7nCqSq

Have a great day :)

**Comment by Elec332** [comment]
Fixed
