### ISSUE TITLE
Crashed when opening, had lots of other mods installed at the time 

### ISSUE THREAD

**Issue by Lothrazar** [Elecs-Mods/CraftingTable-IV#49]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.3.jar)
  LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  bouncybeds (bouncybeds-1.10.2-1.1.jar)
  ForgelinPlugin (Forgelin-1.1.0.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  DualHotbarPlugin (dualhotbar-1.1x-1.7.2.jar)
  HungerTweaks (exhaustion-tweaks-1.10.2-1.1.jar)
  dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 1/22/17 9:30 AM
Description: Rendering screen

java.lang.ClassCastException: sidben.visiblearmorslots.inventory.SlotOffHand cannot be cast to elec332.core.inventory.window.WindowContainer$WidgetLinkedSlot
	at elec332.core.inventory.window.WindowContainer$WindowContainerHandler.getSlot(WindowContainer.java:312)
	at elec332.core.inventory.window.Window.getSlot(Window.java:429)
	at elec332.craftingtableiv.inventory.WindowCraftingTableIV.drawScreen(WindowCraftingTableIV.java:352)
	at elec332.core.inventory.window.WindowGui.func_73863_a(WindowGui.java:93)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at elec332.core.inventory.window.WindowContainer$WindowContainerHandler.getSlot(WindowContainer.java:312)
	at elec332.core.inventory.window.Window.getSlot(Window.java:429)
	at elec332.craftingtableiv.inventory.WindowCraftingTableIV.drawScreen(WindowCraftingTableIV.java:352)
	at elec332.core.inventory.window.WindowGui.func_73863_a(WindowGui.java:93)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: elec332.core.inventory.window.WindowGui
	Mouse location: Scaled: (256, 191). Absolute: (512, 384)
	Screen size: Scaled: (512, 384). Absolute: (1024, 768). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Lothrazar'/221, l='MpServer', x=-44.20, y=64.00, z=-22.58]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-65,64,-6), Chunk: (at 15,4,10 in -5,-1; contains blocks -80,0,-16 to -65,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 71755 game time, 68838 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 24 total; [EntityConcussionCreeper['Concussion Creeper'/3082, l='MpServer', x=6.50, y=63.00, z=-67.50], EntitySheep['Sheep'/141, l='MpServer', x=-6.73, y=75.00, z=51.31], EntityLatchedRenderer['unknown'/273, l='MpServer', x=-44.20, y=64.00, z=-22.58], EntitySheep['Sheep'/152, l='MpServer', x=8.73, y=76.00, z=-45.49], EntitySheep['Sheep'/154, l='MpServer', x=4.76, y=77.00, z=53.34], EntitySheep['Sheep'/155, l='MpServer', x=13.36, y=73.00, z=53.47], EntitySheep['Sheep'/30, l='MpServer', x=-100.65, y=64.00, z=-13.66], EntitySheep['Sheep'/159, l='MpServer', x=22.24, y=74.00, z=-51.31], EntitySheep['Sheep'/160, l='MpServer', x=16.55, y=72.00, z=-61.26], EntitySheep['Sheep'/161, l='MpServer', x=20.95, y=73.00, z=-48.55], EntityZombie['entity.Zombie.name'/3492, l='MpServer', x=-83.50, y=23.00, z=-57.50], EntitySkeleton['Skeleton'/3494, l='MpServer', x=-82.50, y=23.00, z=-56.50], EntityZombie['Zombie'/3640, l='MpServer', x=-38.50, y=18.00, z=-87.50], EntityEnderman['Enderman'/3406, l='MpServer', x=-88.50, y=19.00, z=-57.50], EntityBat['Bat'/3536, l='MpServer', x=22.53, y=31.14, z=26.38], EntitySkeleton['Skeleton'/2649, l='MpServer', x=18.48, y=48.00, z=-13.26], EntityZombie['Zombie'/3427, l='MpServer', x=14.50, y=33.00, z=34.50], EntityPlayerSP['Lothrazar'/221, l='MpServer', x=-44.20, y=64.00, z=-22.58], EntityCreeper['Creeper'/3432, l='MpServer', x=24.50, y=29.00, z=41.50], EntityCreeper['Creeper'/3433, l='MpServer', x=23.50, y=29.00, z=41.50], EntitySkeleton['Skeleton'/3564, l='MpServer', x=-75.50, y=13.00, z=4.50], EntityWitch['Witch'/3452, l='MpServer', x=2.49, y=31.00, z=34.70], EntitySquid['Squid'/126, l='MpServer', x=-48.71, y=60.62, z=-35.40], EntityBat['Bat'/3582, l='MpServer', x=25.17, y=32.39, z=26.35]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 142289528 bytes (135 MB) / 678764544 bytes (647 MB) up to 4277534720 bytes (4079 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 109 mods loaded, 109 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	bouncybeds{1.1} [Bouncy Beds] (minecraft.jar) 
	UCHIJAAAA	forgecreeperheal{2.0.1} [Forge Creeper Heal 2.0.1] ([1.10.2]ForgeCreeperHeal-2.0.1.jar) 
	UCHIJAAAA	Ambience{GRADLE:VERSION-GRADLE:BUILD} [Ambience] (Ambience 1.0-6.jar) 
	UCHIJAAAA	JEI{3.9.5.255} [Just Enough Items] (jei_1.10.2-3.9.5.255.jar) 
	UCHIJAAAA	AppleCore{2.1.0} [AppleCore] (AppleCore-mc1.10.2-2.1.0.jar) 
	UCHIJAAAA	appleskin{1.0.5} [AppleSkin] (AppleSkin-mc1.10.2-1.0.5.jar) 
	UCHIJAAAA	ichunutil{6.1.0} [iChunUtil] (iChunUtil-1.10.2-6.1.0.jar) 
	UCHIJAAAA	attachablegrinder{6.0.0} [AttachableGrinder] (AttachableGrinder-1.10.2-6.0.0.jar) 
	UCHIJAAAA	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	Baubles{1.3.8} [Baubles] (Baubles-1.10.2-1.3.8.jar) 
	UCHIJAAAA	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.10.2-1.1.4.jar) 
	UCHIJAAAA	BetterAchievements{0.3.2.39} [Better Achievements] (BetterAchievements-1.10.2-0.3.2.39.jar) 
	UCHIJAAAA	betterbuilderswands{0.10.2} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.10.2.209+115b204.jar) 
	UCHIJAAAA	betterfoliage{2.1.3} [Better Foliage] (BetterFoliage-MC1.10.2-2.1.3.jar) 
	UCHIJAAAA	BlockDispenser{1.0} [BlockDispenser] (BlockDispenser-1.0-1.jar) 
	UCHIJAAAA	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.10.2-1.5.1.jar) 
	UCHIJAAAA	infinitylib{1.10.2-0.3.0} [InfinityLib] (infinitylib-0.3.0.jar) 
	UCHIJAAAA	boatifull{@MAJOR@.@MINOR@.@REVIS@} [Boatifull] (boatifull-0.4.0.jar) 
	UCHIJAAAA	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCHIJAAAA	BuildersGuides{1.10.2-1.0.2} [Builder's Guides] (buildersguides-1.10.2-1.0.2.jar) 
	UCHIJAAAA	ceramics{1.10.2-1.1.4b} [Ceramics] (Ceramics-1.10.2-1.1.4b.jar) 
	UCHIJAAAA	chameleoncreepers{1.4.1} [Chameleon Creepers] (chameleoncreepers-1.4.1-1.10.2.jar) 
	UCHIJAAAA	ChunkAnimator{1.2} [Chunk Animator] (ChunkAnimator-MC1.9.4-1.2.jar) 
	UCHIJAAAA	clienttweaks{1.1.16} [Client Tweaks] (ClientTweaks_1.10.2-1.1.16.jar) 
	UCHIJAAAA	shadowmc{3.5.0} [ShadowMC] (ShadowMC-1.10.2-3.6.0.jar) 
	UCHIJAAAA	clipboard{@VERSION@} [Clipboard] (Clipboard-1.10.2-1.1.1.jar) 
	UCHIJAAAA	commandkeybindings{6.0.2.10} [Command Keybindings] (CommandKeybindings-Forge-6.0.2.10.jar) 
	UCHIJAAAA	eleccore{1.6.379} [ElecCore] (ElecCore-1.10.2-1.6.379.jar) 
	UCHIJAAAA	craftingtableiv{1.0} [CraftingTable-IV] (CraftingTableIV-1.11-1.4.109.jar) 
	UCHIJAAAA	MineTweaker3{3.0.17} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.17.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.17.jar) 
	UCHIJAAAA	excore{1.6.2} [EXCore] (Excore-1.6.2-1.10.2.jar) 
	UCHIJAAAA	creeperawareness{2.0.2} [Creeper Awareness] (CreeperAwareness-2.0.2-1.10.2.jar) 
	UCHIJAAAA	cs{1.0.3} [Configurable Villager to Door Ratio] (cs-1.0.3.jar) 
	UCHIJAAAA	CustomBackgrounds{1.0} [Custom Backgrounds] (CustomBackgrounds-MC1.9.4-1.1.jar) 
	UCHIJAAAA	cyclicmagic{1.9.18} [Cyclic] (Cyclic-1.10.2-1.9.18.jar) 
	UCHIJAAAA	dailies{1.10.2-6} [Bailey's Dailies] (dailies-1.10.2-6.jar) 
	UCHIJAAAA	darkutils{1.1.6.105} [Dark Utilities] (DarkUtilities-1.10.2-1.1.6.105.jar) 
	UCHIJAAAA	ding{1.0.1} [Ding] (Ding-1.10.2-1.0.1.jar) 
	UCHIJAAAA	disenchanter{1.4} [Disenchanter] (disenchanter-[1.9.4]1.4.jar) 
	UCHIJAAAA	dualhotbar{1.7.2} [Dual Hotbar] (dualhotbar-1.1x-1.7.2.jar) 
	UCHIJAAAA	dsurroundunofficial{3.0.6.1BETA} [Dynamic Surroundings Unofficial] (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UCHIJAAAA	eplus{4.1.0.113} [Enchanting Plus] (EnchantingPlus-1.10.2-4.1.0.115.jar) 
	UCHIJAAAA	endercompass{1.2.3.2} [Ender Compass] (EnderCompass-1.9.x-1.2.3.2.jar) 
	UCHIJAAAA	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCHIJAAAA	extraalchemy{0.3.0.4-hotfix-release} [Extra Alchemy] (extraalchemy-0.3.0.4-hotfix-release.jar) 
	UCHIJAAAA	ExtraRails{1.1.1} [Extra Rails] (ExtraRails-1.10.2-1.1.1.jar) 
	UCHIJAAAA	frt{6.4.5} [Fire's Random Things] (FiresRandomThings-6.4.5.jar) 
	UCHIJAAAA	flighttweaks{0.0.6-alpha} [Flight Tweaks] (flighttweaks-1.10.2-0.0.6-alpha.jar) 
	UCHIJAAAA	ftfloocraft{1.7.6} [Floocraft] (Floocraft-1.7.6.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.5.3-law.jar) 
	UCHIJAAAA	harvestchevsky{b8} [Gentle Harvest] (Gentle_Harvest_1.9_b8.jar) 
	UCHIJAAAA	giacomostravelogue{1.01} [Giacomoâ€™s Travelogue] (GiacomosTravelogue1.10.2-1.01.jar) 
	UCHIJAAAA	GlobalGameRules{2.0} [Global GameRules] (GlobalGameRules-1.10.2-2.0.jar) 
	UCHIJAAAA	grapple_hooks{1.0.8} [Grapple Hooks] (Grapple-Hooks-1.10.2-1.0.8.jar) 
	UCHIJAAAA	gravelminer{4.1.11} [GravelMiner] (GravelMiner_1.10.2-4.1.11.jar) 
	UCHIJAAAA	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
	UCHIJAAAA	helpertools{v3.0c} [HelperTools] (HelperTools-1.10.2-v3.0c.jar) 
	UCHIJAAAA	helpfixer{1.0} [HelpFixer] (HelpFixer-1.10.2-1.4.15.jar) 
	UCHIJAAAA	HoloInventory{2.0.2.141} [HoloInventory] (HoloInventory-1.9.4-2.0.2.141.jar) 
	UCHIJAAAA	HungerInPeace{1.0.0} [Hunger In Peace] (HungerInPeace-mc1.9.4-1.0.0.jar) 
	UCHIJAAAA	inventorysorter{0.10.5+46} [Simple Inventory sorting] (inventorysorter-1.10.2-0.10.5+46.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.3.1} [JourneyMap] (journeymap-1.10.2-5.3.1.jar) 
	UCHIJAAAA	kleeslabs{3.3.5} [KleeSlabs] (KleeSlabs_1.10.2-3.3.5.jar) 
	UCHIJAAAA	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
	UCHIJAAAA	login_shield{1.10.2-19-gd16e7e0} [Login Shield] (Login_Shield-1.10.2-19-gd16e7e0.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.38} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.38-universal.jar) 
	UCHIJAAAA	mineTunes{1.2-9} [mineTunes] (MineTunes 1.2-9.jar) 
	UCHIJAAAA	mobends{0.22.5} [Mo'Bends] (mobends-0.22.5_for_MC-1.10.2.jar) 
	UCHIJAAAA	ModNameTooltip{1.6.0} [Mod Name Tooltip] (modnametooltip_1.10.2-1.6.0.jar) 
	UCHIJAAAA	mtlib{@VERSION@} [MTLib] (MTLib-1.0.0.jar) 
	UCHIJAAAA	modtweaker{2.0.9} [Mod Tweaker] (ModTweaker2-2.0.9.jar) 
	UCHIJAAAA	moreanvils{6.2.0} [More Anvils] (MoreAnvils-6.2.0.jar) 
	UCHIJAAAA	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHIJAAAA	mousetweaks{2.6.4} [Mouse Tweaks] (MouseTweaks-2.6.4-mc1.10.2.jar) 
	UCHIJAAAA	naturescompass{1.3.0} [Nature's Compass] (NaturesCompass-1.10.2-1.3.0.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJAAAA	PeacefulSurface{1.10.2-v3a} [PeacefulSurface] (PeacefulSurface-1.10.2-v3a.jar) 
	UCHIJAAAA	PersistentBits{1.0.6} [Persistent Bits] (PersistentBits-1.10.2-1.0.6.jar) 
	UCHIJAAAA	pcb{1.5.0} [Portable Craft Bench] (portablecraftbench-1.10.2-1.5.0.jar) 
	UCHIJAAAA	progressiveautomation{1.6.53} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.53.jar) 
	UCHIJAAAA	guilib{1.0.7.2} [GUI Library] (PSG Revamped-1.10.2-1.0.0.0.jar) 
	UCHIJAAAA	paintingselgui{1.7.2.0} [PaintingSelectionGui] (PSG Revamped-1.10.2-1.0.0.0.jar) 
	UCHIJAAAA	randomore{1.3.1} [Randomite Ore] (RandomiteOre-1.3.1-MC1.10.2.jar) 
	UCHIJAAAA	redstoneremote{@VERSION@} [Redstone Remote] (RedstoneRemote-1.10.2-1.0.0.jar) 
	UCHIJAAAA	reptilemod{3.5.2} [Reptile Mod] (reptilemod-1.10.2-3.5.2-58.jar) 
	UCHIJAAAA	roughMobs{1.0} [Rough Mobs] (roughMobs1.0.9-1.10.2.jar) 
	UCHIJAAAA	Schematica{1.7.8.153} [Schematica] (Schematica-1.10.2-1.7.8.153-universal.jar) 
	UCHIJAAAA	SimilsaxTranstructors{1.10.2.18} [Similsax Transtructors] (SimilsaxTranstructors-1.10.2.18.jar) 
	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
	UCHIJAAAA	SparksHammers{1.10.2-1.4.3} [Spark's Hammers] (SparksHammers-1.10.2-1.4.3.jar) 
	UCHIJAAAA	spartanshields{1.1c} [Spartan Shields] (SpartanShields-1.10.2-1.1c.jar) 
	UCHIJAAAA	spikemod{1.0.1} [Spike Mod] (spikemod-1.0.1.jar) 
	UCHIJAAAA	Stackie{1.6.0.44} [Stackie] (Stackie-1.10.2-1.6.0.44-universal.jar) 
	UCHIJAAAA	storagenetwork{1.12.10} [Storage Network] (StorageNetwork-1.10.2-1.12.10-final.jar) 
	UCHIJAAAA	supercraftingframe{1.2.1.88} [Super Crafting Frame] (supercraftingframe-1.10.2-1.2.1.88.jar) 
	UCHIJAAAA	tp{1.0.0} [Tiny Progressions] (tinyprogressions-1.10.2-1.0.13.jar) 
	UCHIJAAAA	underphangables{1.0.2} [Underp Hangables] (underphangables-1.10.2-1.0.2.jar) 
	UCHIJAAAA	va{1.10.2-1.6.1} [Vanilla Automation] (va-1.10.2-1.6.1.jar) 
	UCHIJAAAA	vending{1.3.4} [vending] (vending-1.9.4-1.3.4.jar) 
	UCHIJAAAA	visiblearmorslots{2.1-legacy} [Visible Armor Slots] (VisibleArmorSlots[1.10.2]-2.1-legacy.jar) 
	UCHIJAAAA	waddles{0.5.0} [Waddles] (Waddles-1.10.2-0.5.0.jar) 
	UCHIJAAAA	wolfarmor{1.3.1} [Wolf Armor and Storage] (wolfarmor-1.3.1.2.jar) 
	Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
bouncybeds (bouncybeds-1.10.2-1.1.jar)
  bouncy.beds.BouncyBedsTransformer
ForgelinPlugin (Forgelin-1.1.0.jar)
  
AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
DualHotbarPlugin (dualhotbar-1.1x-1.7.2.jar)
  com.rebelkeithy.dualhotbar.DualHotbarTransformer
HungerTweaks (exhaustion-tweaks-1.10.2-1.1.jar)
  qur.tweaks.hunger.EClassTransformer
dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 373.19' Renderer: 'GeForce GT 730/PCIe/SSE2'
	Launched Version: forge-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: GeForce GT 730/PCIe/SSE2 GL version 4.5.0 NVIDIA 373.19, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: OldPortalSounds.zip, Rainy Day.zip, [1.10.2]Dramatic Skys [v1.7].zip, ContrastSymmetry1.0.zip
	Current Language: English (Canada)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz

**Comment by Dalethium** [comment]
I made a fix for this issue, the incompatibility is with visible armor slots -- the fix is here if you want to compile it yourself: https://github.com/Elecs-Mods/ElecCore/pull/87

**Comment by Elec332** [comment]
Fixed in latest latest ElecCore release (build 407)
