### ISSUE TITLE
Typing too fast in the search menu causes it to crash.

### ISSUE THREAD

**Issue by zakhad** [Elecs-Mods/CraftingTable-IV#51]
This is for 1.7.10 and i doubt it'll be hotfixed but I was wondering if I could make the changes myself, but I'm not sure how to do this, any help would be appreicated.

http://pastebin.com/SNE1Z0sq

**Comment by TerminalSnark** [comment]
Can confirm the same problem in 1.11.2 while running a large quantity of other mods.  Given that the display seems to lag somewhat, it's likely overload from the sheer quantity of recipes it's calculating in my case.

http://pastebin.com/UavG5XHu

**Comment by Elec332** [comment]
Il will look into it as it also seems to affect the more recent versions

**Comment by perkinslr** [comment]
Probably need to make it throttle the number of recipes it calculates at a go.  I just got a crash from it trying to play too many of the sounds at once, so I'll probably do this tomorrow if time allows.
