### ISSUE TITLE
Doesn't work with Minecraft 1.10.2

### ISSUE THREAD

**Issue by ozBillo** [Elecs-Mods/CraftingTable-IV#54]
Which version of Forge is recommended with CraftingTableIV-1.4.110.jar and ElecCore-1.10.2-1.7.402.jar Minecraft 1.10.2?

I've tried 13.19.1.2195 and 12.18.3.2239.

Is anyone using this mod successfully with MC 1.10.2?

**Comment by Elec332** [comment]
You need to use ElecCore version 1.7.404
