### ISSUE TITLE
Crash when creating or loading world

### ISSUE THREAD

**Issue by Corruption-Echoes** [Elecs-Mods/CraftingTable-IV#55]
Currently experiencing issues with Loading and  creating worlds, erros and then hangs on building world phase, crash log is here, Seems to be caused by IC2 doing weird shit with an empty recipe for some reason?
http://pastebin.com/HMnJ4WeX

Edit: IDK how to use labels apparently

ElecCore-1.10.2-1.7.405
CraftingTableIV-1.4.110

More information!

After completely removing IC2 and all it's family of mods the following error occurs(Line 892+):
http://pastebin.com/hFv6rZMm

**Comment by pja1982** [comment]
I am also having this issue, I will post my logs when I get home

**Comment by Elec332** [comment]
Fixed in latest latest ElecCore release (build 407)
