### ISSUE TITLE
Crash when placing table

### ISSUE THREAD

**Issue by dragon3025** [Elecs-Mods/CraftingTable-IV#56]
I placed the table and immediately it crashed: http://pastebin.com/mQ0y2N2J

**Comment by ozBillo** [comment]
Same problem here with Minecraft 1.10.2, CraftingTableIV-1.4.110, ElecCore-1.10.2-1.7.409, Forge 2239 and no other mods loaded.

**Comment by pja1982** [comment]
I have the same crash

**Comment by starg09** [comment]
Same crash. Using CT-IV in 1.11.2, versions used:

* CraftingTable-IV 1.4.110
* ElecCore 1.7.409
* Forge 2255

[Crash Report](https://gist.github.com/starg09/16055c629358ed3144ed76155fa8a284)

**Comment by Elec332** [comment]
Fixed by latest ElecCore
