### ISSUE TITLE
Crash on server when opening GUI

### ISSUE THREAD

**Issue by victorbrndls** [Elecs-Mods/CraftingTable-IV#58]
I'm using minecraft 1.11.2 and the latest version of ElecCore(1.7.415) when I try to open my CraftingTableIV(1.4.110) on singleplayer it works, but when I try it on my server it crashes the game not the server

[crash-report](https://pastebin.com/XwHfG8cx)

**Comment by Vaygrim** [comment]
I am getting this exact same thing. [https://pastebin.com/6YV0E1AU](url)
Happens only when I right click open a Crafting Table IV , while on a server. MULTIPLE users get the exact same thing.

**Comment by Harystolho** [comment]
How do i compile the mod ?
