### ISSUE TITLE
CraftingTable IV v1.4.111 causes client to hang when loading world

### ISSUE THREAD

**Issue by Vaygrim** [Elecs-Mods/CraftingTable-IV#59]
Using Forge 2281 under Minecraft 1.10.2 , this latest update to CT4 causes worlds (new or pre-existing) to hang when opening them up in Single Player. Game client just stops responding at "Building Terrain", the CPU usage drops down to 0% .. and it never progresses further. I eventually have to force-quiet the client via Task Manager.

Help?

**Comment by Elec332** [comment]
ffs

**Comment by Vaygrim** [comment]
I have good news, and bad news!
Good news, this issue is fixed and I'm closing it!
(Bad news to come in a new issue! 👍  )
