### ISSUE TITLE
CRASH when using search bar! 

### ISSUE THREAD

**Issue by Vaygrim** [Elecs-Mods/CraftingTable-IV#60]
The hang during startup is fixed. Unfortunately now I'm getting a crash in single player (haven't tested server) while using the search bar. I get 2 or 3 letters in (usually 3) and get the below crash.

[https://pastebin.com/djrieJcx](url)

Honestly I'm not TRYING to find all these bugs, and complicate your existance. 💃

**Comment by Elec332** [comment]
![image](https://cloud.githubusercontent.com/assets/6115944/25147581/49531f6e-2478-11e7-87ee-eb43774826a1.png)
Weird...

**Comment by Elec332** [comment]
Does it also happen if you type a bit slower?

**Comment by Vaygrim** [comment]
Does not seem to be based upon speed, but what's being searched for. I got it to crash three times out of four. The one time it didn't crash I was searching for a vanilla 'Hopper'.

Import [this](https://www.dropbox.com/s/20cfomin7yya8vh/Coop%20Life-0.9-Twitch.zip?dl=0) pack into the Twitch Launcher, and add your latest file versions.. test for yourself.

**Comment by Elec332** [comment]
Very weird, as I have no idea what causes this.
Maybe [this magic version](https://www.dropbox.com/s/sy7kvcvkr84nds5/CraftingTableIV-1.4.113.jar?dl=0) fixes it?
