### ISSUE TITLE
Deduplicate crafting list

### ISSUE THREAD

**Issue by AnrDaemon** [Elecs-Mods/CraftingTable-IV#61]
Sometimes, there's more than one recipe to craft certain item. Sometimes, more than two.
Since there's no apparent way to distinguish different crafting recipes, I think it would make sense to deduplicate the list by the crafting result.
Especially when there's 100+ copies of the same item in the list.

**Comment by Elec332** [comment]
I know this issue exists, but almost every mod needs another way of filtering those out.
Can you please show me a screenshot?

**Comment by AnrDaemon** [comment]
I wouldn't call this a bug per se.
And I wasn't right to say there's no way to distinguish recipes, sorry. I didn't notice material dump at the left.
Here http://prnt.sc/ezu30v all resulting items are the same and input only differs by the sigil metadata (damage).

**Comment by Elec332** [comment]
Should less of an issue in 1.12, please re-open if it has persisted
