### ISSUE TITLE
[Minor Suggestion] Support for Actually Additions' Crafting Table On A Stick

### ISSUE THREAD

**Issue by thegreatersea** [Elecs-Mods/CraftingTable-IV#66]
I'm not sure who would have to add support for this, so I'm adding this suggestion to both repositories. Would it be possible for Crafting Tweaks to support the crafting table on a stick from Actually Additions? As of now, the rotate/rebalance/remove buttons aren't available, and I personally think it would be a nice quality of life feature. I'm not sure if this is something that needs to be done on your end, or if Actually Additions needs to make something available, so as I said I also added this to that repository.

**Comment by thegreatersea** [comment]
wrong repository, ignore this

**Comment by Elec332** [comment]
Hehe, No problem
