### ISSUE TITLE
Mod doesn't work with version of Elec core over 1.6.333

### ISSUE THREAD

**Issue by TheUnderTaker11** [Elecs-Mods/CraftingTable-IV#68]
It simply won't let MC load with any other version than that. This makes it unusable if you want to use deep resonance since it needs a later version than this mod.
Most recent Crafting Table IV file.

**Comment by Elec332** [comment]
I need crash logs in order to do anything

**Comment by TheUnderTaker11** [comment]
I thought I had left a comment... But there is no crash log. It just simply won't let Minecraft load. You know how when it doesn't have a mod at all, forge will stop MC from loading and say "*Blank* mod verion *blank* or about needed" or something similar. It does that, but says it needs a version over 1.6.333, but ONLY works for that version. Makes it impossible to use with deep resonance since that mod requires a higher version. All you have to do is try loading a game with a version higher than that to see it.
