### ISSUE TITLE
1.8.9 No Icon Texture

### ISSUE THREAD

**Issue by FireController1847** [Elecs-Mods/CraftingTable-IV#69]
I know. I'm super late to the game with 1.8.9, but I'm kind of hoping you'll be able to help me out here. I have no idea what's wrong.

CraftingTableIV-1.8.9-1.2.95
ElecCore-1.8.9-1.4.313

![](http://i.imgur.com/zat4Zs0.png)

**Comment by Elec332** [comment]
I assume this version is no longer used by now. I do not have a dev env for ElecCore or CT-IV for 1.8.9 anymore. If there is still demand I may fix this, please open a new issue then.
