### ISSUE TITLE
Crash trying to move items between player inventory and crafting table

### ISSUE THREAD

**Issue by Guardian9978** [Elecs-Mods/CraftingTable-IV#7]
Shift clicking items into or out of your crafting table causes my client to crash with this in SMP.
Error: http://pastebin.com/2gKRS7nA

**Comment by Elec332** [comment]
Hmmm, Ill look into it.

**Comment by Forecaster** [comment]
Same thing happened to me in a singleplayer world

**Comment by Elec332** [comment]
I just got home from holiday, so Ill look into it this weekend

**Comment by Elec332** [comment]
The update should be live any second: http://minecraft.curseforge.com/mc-mods/231840-craftingtable-iv/files
