### ISSUE TITLE
Reissue - unable to craft & cannot detect elec-core version 1.6.333 above 

### ISSUE THREAD

**Issue by PlayOnly** [Elecs-Mods/CraftingTable-IV#70]
Hello, let get straight here:

[Minecraft 1.10.2]

Mod Used:
<a href="https://imgbb.com/"><img src="https://image.ibb.co/hNGGra/report3.png" alt="report3" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>blogger image hosting</a><br />
I also used ElecCore 1.7.425 & ElecCore 1.6.379 one seperate process

Minecraft version:
<a href="https://imgbb.com/"><img src="https://image.ibb.co/jeHd4v/report2.png" alt="report2" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>upload gif online</a><br />
I also, used forge-1.10.2-12.18.3.3.2422 on seperate process

Case 1 - When using ElecCore above 1.6.333, cannot detect ElecCore above 1.6.333, similar issue on #68 maybe?
<a href="https://ibb.co/mhSLjv"><img src="https://preview.ibb.co/koSaHF/report1.png" alt="report1" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>upload image</a><br />

No crash, but here is the log:
Forge-1.10.2-12.18.3.2185: https://pastebin.com/cqm1RnD4
Forge-1.10.2-12.18.3.3.2422: https://pastebin.com/M72KAFPU

Case 2 - Used ElecCore 1.6.333 the mod load but cannot craft, it show something but when click on it it does nothing, similar issue on #38 maybe?
<a href="https://ibb.co/cDdUBa"><img src="https://preview.ibb.co/kotJ4v/report4.png" alt="report4" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>upload a photo on internet</a><br />

No crash, but here is the log:
Forge-1.10.2-12.18.3.2185: https://pastebin.com/keb8bnMW
Forge-1.10.2-12.18.3.3.2422:https://pastebin.com/qu5PF0Tj

I believe i got the latest mods downloaded from:
[crafting table](https://mods.curse.com/mc-mods/minecraft/231840-craftingtable-iv#t1:other-downloads)
[eleccore](https://minecraft.curseforge.com/projects/eleccore-rendering-library/files)

Any idea? Im sorry to issues a separate mod in one issue, i hope you're ok with this.

**Comment by Elec332** [comment]
You are using a very old version, please update to CraftingTableIV version 1.4.113
