### ISSUE TITLE
Mod Conflict

### ISSUE THREAD

**Issue by orionSquared** [Elecs-Mods/CraftingTable-IV#71]
Good evening,

It seems there's a slight mod conflict with the 1.11.2 version of your mod. I have the Concrete Mod installed and when I open the CTIV I am able to pull out fully crafted concrete powder and concrete. This is both with items in my inventory and with an empty inventory (none of those items were items involved in crafting concrete powder).

**Comment by Elec332** [comment]
This did not happen in my test unfortunately
