### ISSUE TITLE
Missing compatibility with 1.12.2

### ISSUE THREAD

**Issue by vaqxai** [Elecs-Mods/CraftingTable-IV#76]
This mod is missing compatibility with minecraft version 1.12.2, throws LoaderExceptionModCrash on startup.

I would update it myself, i'm pretty good with Java but blank at mc mods, no idea where to even start, but if i get some guidance i can pull up a pull request, so that you don't have to do it yourself, @Elec332 . Any help much appreciated.

**Comment by Elec332** [comment]
I have a 1.12 version ready, which will be released at the same time as the ElecCore rewrite, wich will probably be next weekend.

**Comment by vaqxai** [comment]
Thanks a lot! Also, by next you mean 8-10.02 or 15-17.02?

**Comment by vaqxai** [comment]
@Elec332 Where is it?

**Comment by Darinth** [comment]
I apologize, I'm promise I'm not trying to push for a release. I have a 1.12.2 modpack already up and running, but am looking to do some updates to it in the near future. CTIV was a major component of the 1.10 previous version of this pack and I'd like to include it in the update. Is there a chance to see it this weekend (in which case I'll hold off on updating the pack until it comes out) or should I go ahead and do those updates without it?

Thank you for all your hard work Elec.

**Comment by Elec332** [comment]
https://minecraft.curseforge.com/projects/craftingtable-iv/files/2679745

Oops, forgot to close this

**Comment by Darinth** [comment]
You're my hero. <3

Thank you.
