### ISSUE TITLE
Issue with use

### ISSUE THREAD

**Issue by Seiklus** [Elecs-Mods/CraftingTable-IV#78]
https://paste.ee/p/ocDwp

crash on use (right click)
seems to have to do with Immersive engineerings rendering, not sure exactly the details

**Comment by Elec332** [comment]
This should have been fixed in the latest version of ElecCore:
https://www.curseforge.com/minecraft/mc-mods/eleccore/files/2853959

If this hasn't fixed it, please open a new issue.
(I cannot 100% confirm, because the paste is currently unavailable)
