### ISSUE TITLE
Tooltip Crash with Mystical Agriculture

### ISSUE THREAD

**Issue by GeoMak93** [Elecs-Mods/CraftingTable-IV#79]
Opening the table and hovering over a craftible item with Mystical Agriculture installed gives the following crash.
https://paste.ee/p/ZDisK
Believed to be a problem with tooltips; Mystical Agriculture colours the text for some items; could be related to that. Should clarify it's not just for mystical agriculture items, but all items.
Mods:
MysticalAgriculture-1.12.2-1.7.3
Cucumber-1.12.2-1.1.3
ElecCore-1.12.2-1.9.452

**Comment by Darinth** [comment]
Nearly identical crash, except the mod it's interacting with is Botania.
Minecraft 1.12.2
Forge 14.23.5.2811
ElecCore-1.12.2-1.9.452
CraftingTableIV-1.12.2.1.5.116
Botania r1.10-359

https://pastebin.com/fRuDCUzH

**Comment by Darinth** [comment]
Tried adding Botania to the DisableMods in the config file, no impact. Happens as soon as I try to mouse over any item (not just botania items) in the crafting table.

**Comment by pupnewfster** [comment]
For some reason it seems to event's itemstack is null.

**Comment by pupnewfster** [comment]
I think it is because of this https://github.com/Elecs-Mods/CraftingTable-IV/blob/master/src/main/java/elec332/craftingtableiv/inventory/WidgetCraftSlot.java#L52 and maybe wherever else `ItemStackHelper.NULL_STACK` given that returns null. And it should instead be returning an empty item stack, as of I think 1.11 item stacks are not supposed to be null.

**Comment by Darinth** [comment]
Just looked at ElecCore's Github and issues, also peeked at the code. Elec already moved one issue from here to there and has responded. The appropriate issue is at Elecs-Mods/ElecCore#144.

**Comment by Darinth** [comment]
He's already got a fix on github it looks like. He said there should be a new version on CF this weekend.

**Comment by MindlessGalaxies** [comment]
How do I use the fix @Darinth ? I tried taking the code off thre and it just throws up errors if I try to use it

**Comment by kevindevm** [comment]
ye if here is fixed can we compile to a jar file to use it?

**Comment by Elec332** [comment]
This has been fixed in the latest version of ElecCore:
https://www.curseforge.com/minecraft/mc-mods/eleccore/files/2853959
