### ISSUE TITLE
Not crafting

### ISSUE THREAD

**Issue by ghost** [Elecs-Mods/CraftingTable-IV#8]
When ever i press on something in the crafting table to craft nothing happens. I have looked all over the internet to find and answer but haven't been able to find one. Hope to hear back soon Lazer_light1234 :)

**Comment by Elec332** [comment]
Hmmm, what version are you using? What are the exact steps I need to do to reproduct this?

**Comment by ghost** [comment]
Im using beta55

**Comment by ghost** [comment]
and i click then the entire thing refreshes and nothing happens

**Comment by ghost** [comment]
i dont think its the mods i have installed cause vanilla stuff wont craft either so maybe the core needs somethings changing

**Comment by Minizbot2012** [comment]
Having the same issue as lazer, but mine is a dedicated server setup

**Comment by Elec332** [comment]
Hmm, I cannoit replicate this, but im using the latest DEV version. This version should be up on CF soon, and that version _should_ work.
