### ISSUE TITLE
Crash on world load with IC2.

### ISSUE THREAD

**Issue by LumberWizard** [Elecs-Mods/CraftingTable-IV#82]
Crashlog - https://gist.github.com/LumberWizard/a089595639f8a6316e001d04744627eb

To reproduce the crash, launch the game normally with IC2 and CraftingTable IV installed, then exit it and change the `hideSecretRecipes` config option in IC2.ini to false. After launching the game again, it will crash when trying to load any world - existing or newly created.

Minecraft version: 1.12.2
Forge version: 14.23.5.2828
ElecCore version: 1.9.452
CraftingTable IV version: 1.5.116
IC2 version: 2.8.117 (confirmed to also crash with 2.8.116)

**Comment by kevindevm** [comment]
can confirm with "IC2Classic+1.12-1.5.4.2" does not work, please fix ♥

**Comment by Elec332** [comment]
This should have been fixed in the latest version:
https://www.curseforge.com/minecraft/mc-mods/craftingtable-iv/files/2854036

**Comment by LumberWizard** [comment]
My issue was with the real IC2 (AKA IC2 Experimental), and it wasn't fixed by the update.

**Comment by Elec332** [comment]
Weird, as I've done quite some testing with IC2 Exp version 2.8.188-ex112

Which version are you using?

**Comment by LumberWizard** [comment]
Same version. Did you disable the `hideSecretRecipes` config option?

**Comment by Elec332** [comment]
Seems like I didn't.
I got a bit confused when I heard "IC2 classic crashed".

It's been fixed now.
https://www.curseforge.com/minecraft/mc-mods/craftingtable-iv/files/2855023
