### ISSUE TITLE
Client Crash when accessing Crafting Table

### ISSUE THREAD

**Issue by katubug** [Elecs-Mods/CraftingTable-IV#83]
Happens every time I open the table with stuff in my inventory. It starts to populate the recipes and then boots me out. Right now I only have vanilla blocks in there.

My inventory was:
- CraftingTable IV
- 64 Spruce Planks
- 64 Magenta Wool
- 64 Blocks of Iron

Here's the crash:
https://paste.dimdev.org/eguziguwem.mccrash

**Comment by Elec332** [comment]
This has been fixed in the latest version of ElecCore:
https://www.curseforge.com/minecraft/mc-mods/eleccore/files/2853959
