### ISSUE TITLE
Crash with botania (Tooltip)

### ISSUE THREAD

**Issue by dsmtE** [Elecs-Mods/CraftingTable-IV#84]
My game crash when I open the table with of without stuff in my inventory. 

It seems to come from the tooltips management which enters in conflict with botania (or other mods like xNet also...).

Can you fix that please ?

logs :
java.lang.NullPointerException: Rendering screen
vazkii.botania.client.core.handler.TooltipAdditionDisplayHandler.onToolTipRender(TooltipAdditionDisplayHandler.java:50)
net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_TooltipAdditionDisplayHandler_onToolTipRender_PostText.invoke(.dynamic)
net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:409)
elec332.core.inventory.tooltip.ToolTip.renderTooltip(ToolTip.java:55)
elec332.core.inventory.window.Window.drawScreenPost(Window.java:419)
elec332.craftingtableiv.inventory.WindowCraftingTableIV.drawScreenPost(WindowCraftingTableIV.java:414)
elec332.core.inventory.window.WindowGui.func_73863_a(WindowGui.java:98)
net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:497)
net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1457)
net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
net.minecraft.client.main.Main.main(SourceFile:123)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:497)
net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Elec332** [comment]
This has been fixed in the latest version of ElecCore:
https://www.curseforge.com/minecraft/mc-mods/eleccore/files/2853959
