### ISSUE TITLE
Missing Localization

### ISSUE THREAD

**Issue by WenXin20** [Elecs-Mods/CraftingTable-IV#85]
`Minecraft v1.14.4`
`Forge v28.1.109`
`ElecCore v2.0.25-beta`
`Crafting Table IV v1.6.119`

The Crafting Table is missing it's localization, both in the inventory and when it's placed by looking at it with a mod such as Hwyla.

**Comment by Elec332** [comment]
Yep, for some reason I didnt notice Mojang moved to JSON's for lang
