### ISSUE TITLE
Typing 'E' into the search bar exits the gui

### ISSUE THREAD

**Issue by WenXin20** [Elecs-Mods/CraftingTable-IV#87]
`Minecraft v1.14.4`
`Forge v28.1.109`
`ElecCore v2.0.25-beta`
`Crafting Table IV v1.6.119`

In the search bar, if I type the letter `e`, it will instead exit the GUI.

**Comment by Elec332** [comment]
https://github.com/Elecs-Mods/ElecCore/commit/b9443a3d3dccad13eb79757c6b4f4de905c5353a
