### ISSUE TITLE
NPE w/ Pokecube AIO & Glacia

### ISSUE THREAD

**Issue by WenXin20** [Elecs-Mods/CraftingTable-IV#91]
`Minecraft v1.14.4`
`Forge v28.1.109`
`ElecCore v2.0.25-beta`
`Crafting Table IV v1.6.119`
[`Pokecube AIO v2.0.0.c`](https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi)
[`Glacia v14.4.1b`](https://www.curseforge.com/minecraft/mc-mods/glacia-dimension)

There is an NPE if either Glacia or Pokecube AIO is installed when the game tries to load. It might happen with some other mods too. I thought I made an issue for this yesterday, but it seems to have disappeared...

[Full Log](https://gist.github.com/WenXin20/55e8d3c67463b44d5cee472c89180034)

![2020-01-08_13 09 30](https://user-images.githubusercontent.com/12000593/72007805-2172d880-3218-11ea-9d05-da1c6594ba01.png)

**Comment by WenXin20** [comment]
I also noticed that the Crafting Table IV block is using the old oak planks and crafting table textures from 1.12 instead of the new ones from 1.14.

**Comment by Elec332** [comment]
https://github.com/Elecs-Mods/ElecCore/commit/5f8749e5d4e89f10e14201514299acea1fb8de07

The textures are not old. Thats just the model of the CraftingTable-IV.

**Comment by WenXin20** [comment]
After updating to the newer versions, I'm still seeing this issue when Pokecube is installed.
