### ISSUE TITLE
RecipeCache Crash

### ISSUE THREAD

**Issue by WenXin20** [Elecs-Mods/CraftingTable-IV#92]
`Minecraft v1.14.4`
`Forge v28.1.111`
`ElecCore v2.0.30-beta`
`Crafting Table IV v1.6.122`

I got this crash after opening the crafting table. Either this happened because too many items tried to render in at once, or because I started typing in the search bar before any items appeared.

[Crash Report](https://gist.github.com/WenXin20/e6af7fcd4c3c5396be31656611e1b7e6)

**Comment by Elec332** [comment]
https://www.curseforge.com/minecraft/mc-mods/craftingtable-iv/files/2998881
