### ISSUE TITLE
I wanted to craft four charging bazookas, got a crash

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [Elecs-Mods/CraftingTable-IV#93]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (FoamFix_1.12.2_0.10.10.jar)
  MekanismCoremod (Mekanism_1.12.2_9.8.3.390.jar)
  HCASM (HammerCore_1.12.2_2.0.5.6.jar)
  CoreMod (Aroma1997Core_1.12.2_2.0.0.2.b165.jar)
  LoadingPlugin (AdChimneys_1.12.2_3.5.7.0-build.0424.jar)
  WolfArmorCore (WolfArmor_1.12.2_3.3.0.19.jar)
  TenshiCore (TenshiLib_1.12.2_1.2.3.jar)
  Techguns Core (TechGuns_1.12.2_2.0.2.0_pre3.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks_1.12.2_1.64dev.150.jar)
  NWRTweak (RedstonePaste_1.12.2_1.7.5.jar)
  PhosphorFMLLoadingPlugin (Phosphor_1.12.2_0.2.6build50.jar)
  PerformantLoadingPlugin (Performant_1.12.2_1.7.jar)
  LoadingPlugin (Bloodmoon_1.12.2_1.5.3.jar)
  CorePlugin (ForgeEnderTech_1.12.2_4.4.24.0-build.0421.jar)
  RBLoadingPlugin (RealBench_1.12.2_1.3.3.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 1/14/20 10:26 PM
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.NullPointerException
	at elec332.craftingtableiv.network.PacketCraft.onMessageThreadSafe(PacketCraft.java:33)
	at elec332.core.network.packets.AbstractPacket$1.run(AbstractPacket.java:34)
	at elec332.core.handler.TickHandler.processSingleTicks(TickHandler.java:88)
	at elec332.core.handler.TickHandler.access$100(TickHandler.java:17)
	at elec332.core.handler.TickHandler$1.onTick(TickHandler.java:28)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_605__onTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at techguns.recipes.AmmoSumRecipeFactory$AmmoSumRecipe.func_77572_b(AmmoSumRecipeFactory.java:58)
	at elec332.craftingtableiv.api.IRecipeHandler.getCraftingResult(IRecipeHandler.java:54)
	at elec332.craftingtableiv.handler.CraftingHandler.canCraft(CraftingHandler.java:207)
	at elec332.craftingtableiv.handler.CraftingHandler.maxCraft(CraftingHandler.java:166)
	at elec332.craftingtableiv.handler.CraftingHandler.canCraft(CraftingHandler.java:154)
	at elec332.craftingtableiv.handler.CraftingHandler.onMessageReceived(CraftingHandler.java:354)
	at elec332.craftingtableiv.network.PacketCraft.onMessageThreadSafe(PacketCraft.java:31)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4833126856 bytes (4609 MB) / 11533811712 bytes (10999 MB) up to 28631367680 bytes (27305 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 5, allocated: 13, tallocated: 96
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 140 mods loaded, 140 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version              | Source                                        | Signature                                |
	|:------ |:--------------------- |:-------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2               | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                   | 9.42                 | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                   | 8.0.99.99            | forge-1.12.2-14.23.5.2847-universal.jar       | None                                     |
	| LCHIJA | forge                 | 14.23.5.2847         | forge-1.12.2-14.23.5.2847-universal.jar       | None                                     |
	| LCHIJA | foamfixcore           | 7.7.4                | minecraft.jar                                 | None                                     |
	| LCHIJA | techguns_core         | 1.12.2-1.0           | minecraft.jar                                 | None                                     |
	| LCHIJA | jei                   | 4.15.0.291           | Jei_1.12.2_4.15.0.291.jar                     | None                                     |
	| LCHIJA | abyssalcraft          | 1.9.15               | AbyssalCraft_1.12.2_1.9.15.jar                | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | aroma1997core         | 2.0.0.2.b165         | Aroma1997Core_1.12.2_2.0.0.2.b165.jar         | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | aromabackup           | 3.0.0.0.b129         | AromaBackup_1.12.2_3.0.0.0.b129.jar           | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | aromabackuprecovery   | 3.0.0.0.b129         | AromaBackup_1.12.2_3.0.0.0.b129.jar           | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | badmobs               | 1.1.40               | BadMobs_1.12.2_1.1.40.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | baubles               | 1.5.2                | Baubles_1.12.2_1.5.2.jar                      | None                                     |
	| LCHIJA | betteranimalsplus     | 7.1.0                | BetterAnimalsplus_1.12.2_7.1.0.jar            | None                                     |
	| LCHIJA | betterbuilderswands   | 0.13.2               | BetterBuildersWands_1.12.2_0.13.2.271.jar     | None                                     |
	| LCHIJA | biomesoplenty         | 7.0.1.2444           | BiomesOPlenty_1.12.2_7.0.1.2444.jar           | None                                     |
	| LCHIJA | blocklings            | 6.0.1                | Blocklings_1.12.2_6.0.1.jar                   | None                                     |
	| LCHIJA | bloodmoon             | 1.5.3                | Bloodmoon_1.12.2_1.5.3.jar                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | bookshelf             | 2.3.589              | BookShelf_1.12.2_2.3.589.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bountifulbaubles      | 0.0.1                | BountifulBaubles_1.12.2_0.1.4.jar             | None                                     |
	| LCHIJA | codechickenlib        | 3.2.3.358            | CodeChickenLib_1.12.2_3.2.3.358.jar           | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux          | 2.1.0                | RedstoneFlux_1.12.2_2.1.0.6.jar               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | brandonscore          | 2.4.17               | BrandonScore_1.12.2_2.4.17.208.jar            | None                                     |
	| LCHIJA | bspkrscore            | 7.6.0.1              | BspkrScore_1.12.2_7.6.0.1.jar                 | None                                     |
	| LCHIJA | buildcraftlib         | 7.99.24.1            | BuildCraftALL_1.12.2_7.99.24.1.jar            | None                                     |
	| LCHIJA | buildcraftcore        | 7.99.24.1            | BuildCraftALL_1.12.2_7.99.24.1.jar            | None                                     |
	| LCHIJA | buildcraftbuilders    | 7.99.24.1            | BuildCraftALL_1.12.2_7.99.24.1.jar            | None                                     |
	| LCHIJA | buildcrafttransport   | 7.99.24.1            | BuildCraftALL_1.12.2_7.99.24.1.jar            | None                                     |
	| LCHIJA | buildcraftsilicon     | 7.99.24.1            | BuildCraftALL_1.12.2_7.99.24.1.jar            | None                                     |
	| LCHIJA | crafttweaker          | 4.1.19               | CraftTweaker2_1.12.2_4.1.19.jar               | None                                     |
	| LCHIJA | theoneprobe           | 1.4.28               | TheOneProbe_1.12.2_1.4.28.jar                 | None                                     |
	| LCHIJA | buildcraftcompat      | 7.99.24.1            | BuildCraftALL_1.12.2_7.99.24.1.jar            | None                                     |
	| LCHIJA | buildcraftenergy      | 7.99.24.1            | BuildCraftALL_1.12.2_7.99.24.1.jar            | None                                     |
	| LCHIJA | buildcraftfactory     | 7.99.24.1            | BuildCraftALL_1.12.2_7.99.24.1.jar            | None                                     |
	| LCHIJA | buildcraftrobotics    | 7.99.24.1            | BuildCraftALL_1.12.2_7.99.24.1.jar            | None                                     |
	| LCHIJA | carryon               | 1.12.3               | CarryOn_1.12.2_1.12.3.jar                     | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | champions             | 1.12.2-1.0.11        | Champions_1.12.2_1.0.11.jar                   | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | chickenchunks         | 2.4.2.74             | ChickenChunks_1.12.2_2.4.2.74.jar             | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | refinedstorage        | 1.6.15               | RefinedStorage_1.12.2_1.6.15.jar              | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | compactmachines3      | 3.0.18               | CompactMachines3_1.12.2_3.0.18-b281.jar       | None                                     |
	| LCHIJA | eleccore              | 1.9.453              | ElecCore_1.12.2_1.9.453.jar                   | None                                     |
	| LCHIJA | craftingtableiv       | 1.12.2-1.5.120       | CraftingTableIV_1.12.2_1.5.120.jar            | None                                     |
	| LCHIJA | craftingtweaks        | 8.1.9                | CraftingTweaks_1.12.2_8.1.9.jar               | None                                     |
	| LCHIJA | crafttweakerjei       | 2.0.3                | CraftTweaker2_1.12.2_4.1.19.jar               | None                                     |
	| LCHIJA | creepingnether        | 2.2.2                | CreepingNether_1.12.2_2.2.2.jar               | None                                     |
	| LCHIJA | cucumber              | 1.1.3                | Cucumber_1.12.2_1.1.3.jar                     | None                                     |
	| LCHIJA | customizeddungeonloot | 1.0.3                | CustomizedDungeonLoot_1.12.2_1.0.3.jar        | None                                     |
	| LCHIJA | customnpcs            | 1.12                 | CustomNPCs_1.12.2_01Oct19.jar                 | None                                     |
	| LCHIJA | dmonsters             | 1.7                  | DeadlyMonsters_1.12.2_1.71.jar                | None                                     |
	| LCHIJA | disenchanter          | 1.6                  | DisenChanter_1.12.2_1.121.6.jar               | None                                     |
	| LCHIJA | dldungeonsjbg         | 1.12.10              | DoomlikeDungeons_1.12.2_1.12.10.jar           | None                                     |
	| LCHIJA | draconicevolution     | 2.3.24               | DraconicEvolution_1.12.2_2.3.24.349.jar       | None                                     |
	| LCHIJA | mocreatures           | 12.0.5               | DrZharksMoCreaturesMod_1.12.2_12.0.5.jar      | None                                     |
	| LCHIJA | dungeonmobs           | 5.8.4                | DungeonMobs_1.12.2_5.8.4.jar                  | None                                     |
	| LCHIJA | easybreeding          | 5.0.0                | EasyBreading_1.12.2_5.0.0.jar                 | None                                     |
	| LCHIJA | eplus                 | 5.0.179              | EnchantingPlus_1.12.2_5.0.179.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | enemyz                | 0.1.2                | Enemyz_1.12.2_0.1.2.jar                       | None                                     |
	| LCHIJA | epicsiegemod          | 13.165               | EpicSiegeMod_1.12.2_13.165.jar                | None                                     |
	| LCHIJA | extraanvils           | @VERSION@            | ExtraAnvils_1.12.2_0.9.jar                    | None                                     |
	| LCHIJA | zerocore              | 1.12.2-0.1.2.8       | ZeroCore_1.12.2_0.1.2.8.jar                   | None                                     |
	| LCHIJA | bigreactors           | 1.12.2-0.4.5.67      | ExtremeReactors_1.12.2_0.4.5.67.jar           | None                                     |
	| LCHIJA | familiarfauna         | 1.0.11               | FamiliarFauna_1.12.2_1.0.11.jar               | None                                     |
	| LCHIJA | fapdosnethermobs      | 1.1.0                | FapdosNetherMobs_1.12.2_1.1.0.jar             | None                                     |
	| LCHIJA | ffenchants            | 1.1.5                | FFEnchants_1.12.2_1.1.5.jar                   | None                                     |
	| LCHIJA | foamfix               | 0.10.10-1.12.2       | FoamFix_1.12.2_0.10.10.jar                    | None                                     |
	| LCHIJA | forgeendertech        | 1.12.2-4.4.24.0      | ForgeEnderTech_1.12.2_4.4.24.0-build.0421.jar | None                                     |
	| LCHIJA | ftblib                | 5.4.3.141            | FTBLib_1.12.2_5.4.3.141.jar                   | None                                     |
	| LCHIJA | ftbutilities          | 5.4.0.107            | FTBUtilities_1.12.2_5.4.0.107.jar             | None                                     |
	| LCHIJA | giacomosfoundry       | 1.3.13               | GiacomosFoundry_1.12.2_1.3.13.jar             | None                                     |
	| LCHIJA | goblin_mod_reforged   | 1.0.0                | GoblinMod_1.12.2_1.0.1.jar                    | None                                     |
	| LCHIJA | grimoireofgaia        | 1.6.9.3              | GrimoireOfGaia3_1.12.2_1.6.9.3.jar            | None                                     |
	| LCHIJA | grimpack              | 6.0.0.6              | GrimPack_1.12.2_6.0.0.6.jar                   | None                                     |
	| LCHIJA | hammercore            | 2.0.5.6              | HammerCore_1.12.2_2.0.5.6.jar                 | None                                     |
	| LCHIJA | holoinventory         | 2.1.1.151            | HoloInventory_1.12.2_2.1.1.151.jar            | None                                     |
	| LCHIJA | improvableskills      | 65r                  | ImprovableSkills_1.12.2_65r.jar               | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | improvedbackpacks     | 1.12.2-1.4.0.0       | ImprovedBackpacks_1.12.2_1.4.0.0.jar          | None                                     |
	| LCHIJA | improvedmobs          | 1.6.2                | ImprovedMobs_1.12.2_1.6.2.jar                 | None                                     |
	| LCHIJA | infernalmobs          | 1.7.6                | InfernalMobs_1.12.2_1.7.7.jar                 | None                                     |
	| LCHIJA | kjlib                 | 1.0.4                | KJLib_1.12.2_1.0.4.jar                        | None                                     |
	| LCHIJA | inventorygenerators   | 1.2.2                | InventoryGenerators_1.12.2_1.2.2.jar          | None                                     |
	| LCHIJA | inventorytweaks       | 1.64+dev.150.7168e7a | InventoryTweaks_1.12.2_1.64dev.150.jar        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest             | 1.12.2-7.0.67.844    | IronChest_1.12.2_7.0.72.847.jar               | None                                     |
	| LCHIJA | ironfurnaces          | 1.3.5                | IronFurnaces_1.12.2_1.3.5.jar                 | None                                     |
	| LCHIJA | ironjetpacks          | 1.1.0                | IronJetpacks_1.12.2_1.1.0.jar                 | None                                     |
	| LCHIJA | iymts_mod             | 1.12.2-0.0.6         | Iyamatos_mod_1.12.2_0.0.6.jar                 | None                                     |
	| LCHIJA | iymts_mob_mod         | 0.2.1                | Iymts_Mob_Mod_1.12.2_2611_ver.0.2.1.jar       | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.5.6         | JourneyMap_1.12.2_5.5.6.jar                   | None                                     |
	| LCHIJA | jecalculation         | 1.12.2-3.2.2         | JustEnoughCalculation_1.12.2_3.2.2.jar        | None                                     |
	| LCHIJA | laggoggles            | FAT-1.12.2-4.8       | LagGoggles_1.12.2_4.8.jar                     | None                                     |
	| LCHIJA | lootbags              | 2.5.8.5              | LootBags_1.12.2_2.5.8.5.jar                   | None                                     |
	| LCHIJA | lucky                 | 7.6.0                | LuckyBlock_1.12.2_7.6.0.zip                   | None                                     |
	| LCHIJA | mekanism              | 1.12.2-9.8.3.390     | Mekanism_1.12.2_9.8.3.390.jar                 | None                                     |
	| LCHIJA | mekanismgenerators    | 1.12.2-9.8.3.390     | MekanismGenerators_1.12.2_9.8.3.390.jar       | None                                     |
	| LCHIJA | techguns              | 2.0.2.0              | TechGuns_1.12.2_2.0.2.0_pre3.1.jar            | None                                     |
	| LCHIJA | mekores               | 2.0.12               | MekanismOres_1.12.2_2.0.12.jar                | None                                     |
	| LCHIJA | mekanismtools         | 1.12.2-9.8.3.390     | MekanismTools_1.12.2_9.8.3.390.jar            | None                                     |
	| LCHIJA | naturescompass        | 1.8.0                | NaturesCompass_1.12.2_1.8.0.jar               | None                                     |
	| LCHIJA | recipehandler         | 0.13                 | NoMoreRecipeConflict_1.12.2_0.131.12.2.jar    | None                                     |
	| LCHIJA | omlib                 | 3.1.3-246            | Omlib_1.12.2_3.1.3-246.jar                    | None                                     |
	| LCHIJA | openmodularturrets    | 3.1.4-356            | OpenModularTurrets_1.12.2_3.1.4-356.jar       | None                                     |
	| LCHIJA | overlord              | 2.4.14               | Overlord_1.12.2_2.4.14.jar                    | None                                     |
	| LCHIJA | performant            | 1.12.2-1.4           | Performant_1.12.2_1.7.jar                     | None                                     |
	| LCHIJA | potioncore            | 1.8_for_1.12.2       | PotionCore_1.12.2_1.8.jar                     | None                                     |
	| LCHIJA | prefab                | 1.3.0.26             | PreFab_1.12.2_1.3.0.26.jar                    | None                                     |
	| LCHIJA | projectintelligence   | 1.0.9                | ProjectIntelligence_1.12.2_1.0.9.28.jar       | None                                     |
	| LCHIJA | qualitytools          | 1.0.7_for_1.12.2     | QualityTools_1.12.2_1.0.7.jar                 | None                                     |
	| LCHIJA | redstonepaste         | 1.7.5                | RedstonePaste_1.12.2_1.7.5.jar                | None                                     |
	| LCHIJA | refinedstorageaddons  | 0.4.4                | RefinedStorageAddons_1.12.2_0.4.4.jar         | None                                     |
	| LCHIJA | retorch               | 1r                   | ReTorch_1.12.2_1r.jar                         | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | roguelike             | 1.8.0                | RoguelikeDungeons_1.12.2_1.8.0.jar            | None                                     |
	| LCHIJA | ropebridge            | 2.0.5                | RopeBridge_1.12.2_2.0.7.jar                   | None                                     |
	| LCHIJA | roughmobs             | 2.0.0                | RoughMobs2_1.12.2_2.0.15.jar                  | None                                     |
	| LCHIJA | ruins                 | 17.2                 | Ruins_1.12.2.jar                              | None                                     |
	| LCHIJA | satako                | 2.26                 | Satako_1.12.2_2.26.jar                        | None                                     |
	| LCHIJA | sdrones               | 1.3.1                | Sdrones_1.12.2_1.3.1.jar                      | None                                     |
	| LCHIJA | signedit              | 1.12.2-4             | SignEdit_1.12.2_4.jar                         | None                                     |
	| LCHIJA | simplefluidtanks      | 1.12.2-1.7.1.3       | SimpleFluidTanks_1.12.2_1.7.1.3.jar           | None                                     |
	| LCHIJA | simplequarry          | 27r                  | SimpleQuarry_1.12.2_27r.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | sophisticatedwolves   | 3.13.8               | SophisticatedWolves_1.12.2_3.13.8.jar         | None                                     |
	| LCHIJA | spartanshields        | 1.5.4                | SpartanShields_1.12.2_1.5.4.jar               | None                                     |
	| LCHIJA | specialmobs           | 1.0.2_for_mc1.12.2   | SpecialMobs_1.12.2_1.0.2.jar                  | None                                     |
	| LCHIJA | srparasites           | 1.3.0                | SRParasites_1.12.2v1.4.0.jar                  | None                                     |
	| LCHIJA | statuseffecthud       | 1.43.0               | StatusEffectHud_1.12.2_1.43.0.jar             | None                                     |
	| LCHIJA | teleportingxp         | 1.1.1.1              | TeleportingXP_1.12.2_1.1.1.1.jar              | None                                     |
	| LCHIJA | tenshilib             | 1.2.3                | TenshiLib_1.12.2_1.2.3.jar                    | None                                     |
	| LCHIJA | topaddons             | 1.12.2-1.12.0        | TOPAddons_1.12.2_1.12.0.jar                   | None                                     |
	| LCHIJA | torcharrowsmod        | 1.12.1-3             | TorchArrows_1.12.2_3.jar                      | None                                     |
	| LCHIJA | treechopper           | 1.2.4                | TreeChopper_1.12.2_1.2.4.jar                  | None                                     |
	| LCHIJA | uteamcore             | 2.2.4.133            | U_Team_Core_1.12.2_2.2.4.133.jar              | None                                     |
	| LCHIJA | uncraftingtable       | 1.8-beta6            | UncraftingTable_1.12.2_1.8-beta6.jar          | None                                     |
	| LCHIJA | naturalabsorption     | 1.0.0_for_mc1.12.2   | UnnaturalAbsorption_1.12.2_1.0.0.jar          | None                                     |
	| LCHIJA | upsizer               | 4.0.1                | UpSizer_1.12.2_4.0.1.jar                      | None                                     |
	| LCHIJA | usefulrailroads       | 1.1.1.9              | Useful_RailRoads_1.12.2_1.1.1.9.jar           | None                                     |
	| LCHIJA | wolfarmor             | 3.3.0.19             | WolfArmor_1.12.2_3.3.0.19.jar                 | None                                     |
	| LCHIJA | craftstudioapi        | 1.0.0                | CraftStudio-1.0.1.95-mc1.12-alpha.jar         | None                                     |
	| LCHIJA | cyclopstek            | 1.0.34               | CyclopStek_1.12.2_1.0.34.jar                  | None                                     |
	| LCHIJA | phosphor-lighting     | 1.12.2-0.2.6         | Phosphor_1.12.2_0.2.6build50.jar              | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCHIJA | adchimneys            | 1.12.2-3.5.7.0       | AdChimneys_1.12.2_3.5.7.0-build.0424.jar      | None                                     |
	| LCHIJA | eleccoreloader        | 1.9.453              | ElecCore_1.12.2_1.9.453.jar                   | None                                     |
	| LCHIJA | minersadvantage       | 1.3.19.242           | MinersAdvantage-1.12.2-1.3.19.243.jar         | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (FoamFix_1.12.2_0.10.10.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
MekanismCoremod (Mekanism_1.12.2_9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
HCASM (HammerCore_1.12.2_2.0.5.6.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
CoreMod (Aroma1997Core_1.12.2_2.0.0.2.b165.jar)
  
LoadingPlugin (AdChimneys_1.12.2_3.5.7.0-build.0424.jar)
  com.endertech.minecraft.mods.adchimneys.world.WorldData$BlockRandomTick
WolfArmorCore (WolfArmor_1.12.2_3.3.0.19.jar)
  
TenshiCore (TenshiLib_1.12.2_1.2.3.jar)
  com.flemmli97.tenshilib.asm.ASMTransformer
Techguns Core (TechGuns_1.12.2_2.0.2.0_pre3.1.jar)
  techguns.core.TechgunsASMTransformer
Inventory Tweaks Coremod (InventoryTweaks_1.12.2_1.64dev.150.jar)
  invtweaks.forge.asm.ContainerTransformer
NWRTweak (RedstonePaste_1.12.2_1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
PhosphorFMLLoadingPlugin (Phosphor_1.12.2_0.2.6build50.jar)
  
PerformantLoadingPlugin (Performant_1.12.2_1.7.jar)
  
LoadingPlugin (Bloodmoon_1.12.2_1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
CorePlugin (ForgeEnderTech_1.12.2_4.4.24.0-build.0421.jar)
  
RBLoadingPlugin (RealBench_1.12.2_1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
	HammerCore Debug Information: 
Dependent Mods:
    -Improvable Skills (improvableskills) @65r
    -Simple Quarry (simplequarry) @27r

	Grim Pack loaded parts: 
	= Grim Core { Loaded }
		~ Enable aluminum subpart { Enabled }
		~ Enable coal subpart { Enabled }
		~ Enable graphite subpart { Disabled }
		~ Enable iron subpart { Enabled }
		~ Enable rubber subpart { Enabled }
		~ Enable steel subpart { Enabled }
	= Grim Decor { Loaded }
		~ Enable SubPart alarm { Enabled }
		~ Enable SubPart cages { Enabled }
		~ Enable SubPart calendar { Enabled }
		~ Enable SubPart colorizer { Enabled }
		~ Enable SubPart decorations { Enabled }
		~ Enable SubPart fireplaces { Enabled }
		~ Enable SubPart flat item frame { Enabled }
		~ Enable SubPart fluro { Enabled }
		~ Enable SubPart frames { Enabled }
		~ Enable SubPart furniture { Enabled }
		~ Enable SubPart lamp posts { Enabled }
		~ Enable SubPart lanterns { Enabled }
		~ Enable SubPart lightbulbs { Enabled }
		~ Enable SubPart neon sign { Enabled }
		~ Enable SubPart slopes { Enabled }
		~ Enable SubPart wall clock { Enabled }
		~ Enable SubPart wallpaper { Enabled }
	= Grim Industry { Loaded }
		~ Enable SubPart bridges { Enabled }
		~ Enable SubPart chunk loader { Enabled }
		~ Enable SubPart conveyor { Enabled }
		~ Enable SubPart decoration { Enabled }
		~ Enable SubPart doors { Enabled }
		~ Enable SubPart elemental blocks { Enabled }
		~ Enable SubPart extruder { Enabled }
		~ Enable SubPart fans { Enabled }
		~ Enable SubPart gates { Enabled }
		~ Enable SubPart gravity { Enabled }
		~ Enable SubPart hlights { Enabled }
		~ Enable SubPart ice maker { Enabled }
		~ Enable SubPart machines { Enabled }
		~ Enable SubPart metal works { Enabled }
		~ Enable SubPart nuclear { Disabled }
		~ Enable SubPart rways { Enabled }
		~ Enable SubPart sensors { Enabled }
		~ Enable SubPart shaped charges { Disabled }
		~ Enable SubPart spikes { Enabled }
		~ Enable SubPart steel { Enabled }
		~ Enable SubPart storage { Enabled }
		~ Enable SubPart torches { Enabled }
		~ Enable SubPart workbench upgrades { Enabled }
	= Grim Tools { Loaded }
		~ Enable SubPart backpacks { Disabled }
		~ Enable SubPart black diamond { Enabled }
		~ Enable SubPart boomerangs { Enabled }
		~ Enable SubPart buckets { Enabled }
		~ Enable SubPart chicken suit { Enabled }
		~ Enable SubPart chisel { Disabled }
		~ Enable SubPart detonators { Enabled }
		~ Enable SubPart extinguisher { Enabled }
		~ Enable SubPart grenade launcher { Enabled }
		~ Enable SubPart hammers { Disabled }
		~ Enable SubPart knives { Disabled }
		~ Enable SubPart machetes { Disabled }
		~ Enable SubPart magic { Enabled }
		~ Enable SubPart masks { Disabled }
		~ Enable SubPart multitools { Enabled }
		~ Enable SubPart pokeball { Enabled }
		~ Enable SubPart portable workbench { Disabled }
		~ Enable SubPart powerstaff { Disabled }
		~ Enable SubPart ray guns { Enabled }
		~ Enable SubPart slingshots { Disabled }
		~ Enable SubPart spears { Enabled }
		~ Enable SubPart staffs { Disabled }
		~ Enable SubPart ultimate fist { Disabled }
		~ Enable SubPart wands { Disabled }
	= Grim Util { Loaded }
		~ Enable SubPart auto item replacer { Disabled }
		~ Enable SubPart auto torch { Enabled }
		~ Enable SubPart chicken feathers { Enabled }
		~ Enable SubPart debug { Disabled }
		~ Enable SubPart double doors { Enabled }
		~ Enable SubPart frozen { Enabled }
		~ Enable SubPart fusrodah { Disabled }
		~ Enable SubPart graves { Enabled }
		~ Enable SubPart infinite lava { Disabled }
		~ Enable SubPart time { Enabled }
	= Grim World { Loaded }
		~ Enable SubPart 8-bit mobs { Enabled }
		~ Enable SubPart corruption { Disabled }
		~ Enable SubPart desert wells { Enabled }
		~ Enable SubPart flat bedrock { Enabled }
		~ Enable SubPart floating island world type { Disabled }
		~ Enable SubPart floating islands { Enabled }
		~ Enable SubPart fungus { Enabled }
		~ Enable SubPart glowstone seeds { Enabled }
		~ Enable SubPart gunpowder reeds { Enabled }
		~ Enable SubPart ice pixie { Enabled }
		~ Enable SubPart more people { Disabled }
		~ Enable SubPart randomite { Enabled }
		~ Enable SubPart ruins { Enabled }
		~ Enable SubPart treasure mobs { Enabled }
		~ Enable SubPart world gen expanded { Enabled }

	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['xxxLEOPARDxxx'/150372, l='World', x=207.51, y=33.06, z=275.62]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

https://gist.github.com/xxxLEOPARDxxx/90cb2cb24a1852ee873d1d7a35fb8db2#file-gistfile1-txt

**Comment by Elec332** [comment]
This is a bug in the TechGuns2 mod, the mod author forgot a null check here: https://github.com/pWn3d1337/Techguns2/blob/master/src/main/java/techguns/recipes/AmmoSumRecipeFactory.java#L57
