### ISSUE TITLE
Not loading CraftTweaker recipes, and possibly others.

### ISSUE THREAD

**Issue by MechanosG** [Elecs-Mods/CraftingTable-IV#95]
Someone mentioned this in the curseforge comments, but I haven't seen an issue here about it, so I figured I'd make one.  If you make a recipe with CraftTweaker, CraftingTableIV doesn't seem to see the recipe and is unable to craft it, as if the recipes CraftingTableIV uses were cached before CraftTweaker made any changes or something.  The recipe works in a normal crafting bench however.

I also noticed that there may be other recipes it's not loading too.  Such as UndergroundBiome's recipe of 4 mod cobblestone to make 4 vanilla cobblestone.  Either by intention or due to a bug, the recipe doesn't show up in JEI, but does in fact work in normal crafting.  CraftingTableIV is unable to detect and use it though, unfortunately.

MC 1.12.2
forge-14.23.5.2847
CraftingTableIV-1.12.2-1.5.121.jar
CraftTweaker2-1.12-4.1.20.jar
UndergroundBiomesConstructs-1.12-1.3.7.jar

**Comment by Elec332** [comment]
https://www.curseforge.com/minecraft/mc-mods/craftingtable-iv/files/2998879
