### ISSUE TITLE
Not retaining inventory yet breaks with one punch?

### ISSUE THREAD

**Issue by MechanosG** [Elecs-Mods/CraftingTable-IV#96]
I suggest making it a lot more difficult to break and/or making the inventory not get destroyed when you break it.  Just now I was clearing grass that had grown in the middle of a new incomplete base, and I accidentally punched the CraftingTableIV block.  This instantly broke the table, and destroyed a bunch of tools and resources inside it.  You can imagine my surprise lol.

MC 1.12.2
forge-14.23.5.2847
CraftingTableIV-1.12.2-1.5.121.jar

**Comment by Elec332** [comment]
https://www.curseforge.com/minecraft/mc-mods/craftingtable-iv/files/2998879
