### ISSUE TITLE
ConcurrentModificationException Crash

### ISSUE THREAD

**Issue by MechanosG** [Elecs-Mods/CraftingTable-IV#97]
While using the table, this crash happened.

[crash-2020-02-12_17.11.20-client.txt](https://github.com/Elecs-Mods/CraftingTable-IV/files/4196011/crash-2020-02-12_17.11.20-client.txt)

MC 1.12.2
forge-14.23.5.2847
CraftingTableIV-1.12.2-1.5.121.jar

**Comment by Elec332** [comment]
https://www.curseforge.com/minecraft/mc-mods/craftingtable-iv/files/2998879
